### ISSUE TITLE
Problems with using libraries in gradle project

### ISSUE THREAD

**Issue by azakordonets** [mambu-gmbh/Mambu-APIs-Java#164]
Hi, 

I was trying to incorporate your libraries in my test project in order to write some integration tests. Here's what i did : 
1. I have downloaded 
```
Mambu-APIs-Java-6.0-bin-sources.jar
Mambu-APIs-Java-6.0-bin.jar
mambu-models-V6.0.jar
```
2. I have deployed them to our internal Nexus : 
```
mvn deploy:deploy-file -DgroupId=Mambu-APIs-Java -DartifactId=Mambu-APIs-Java -Dversion=6.0-bin -Dpackaging=jar -Dfile=Mambu-APIs-Java-6.0-bin.jar -Dfile=Mambu-APIs-Java-6.0-bin-sources.jar -DgeneratePom=true -DrepositoryId=releases -Durl=https://{nexus.url}/repository/maven-releases/
```

```
mvn deploy:deploy-file -DgroupId=com.mambu -DartifactId=mambumodels -Dversion=6 -Dpackaging=jar -Dfile=mambu-models-V6.0.jar -DgeneratePom=true -DrepositoryId=releases -Durl=https://nexus.url/repository/maven-releases/
```

In my `build.gradle` file I have added next dependencies : 
```
compile group: 'Mambu-APIs-Java', name: 'Mambu-APIs-Java', version: '6.0-bin'
compile group: 'com.mambu', name: 'mambumodels', version: '6'
```

However, when I try to do something like this : 
```java
MambuAPIServiceFactory serviceFactory = MambuAPIServiceFactory.getFactory(
	"mydomain.mambu.com", "username", "password");
```

I see that `MambuAPIServiceFactory` cannot be found. 

How should I properly include your libraries into my project?

**Comment by acostros** [comment]
Hi Andrew,

Here are some checks that might help you:
 - complementary to adding the dependencies in **_build.gradle_** you also need to make sure that you instruct Gradle to look into your private repository (Nexus) for the dependencies (the one you used in your deploy for "-**Durl**" argument), otherwise Gradle won't know where to download your dependencies from. 
Here is an example:
```
repositories {
....
    maven {
          url "http://nexus.url/repository/maven-releases" 
    }
.....
}
```

 -  check that the **mvn deploy** command can handle 2 "-**Dfile**" arguments. From my knowledge the **_mvn deploy_** command supports only one "-**Dfile**" argument.
 This means with your command you are deploying to Nexus only the jar indicated by "**-Dfile=Mambu-APIs-Java-6.0-bin-sources.jar"** , since is the second argument, will override the previous one and you will end up having only the sources in your Nexus repository and no binaries.
If you want to use the same groupId and artefactId you may use the Nexus UI which allows you to set a classifier, otherwise through the **_mvn deploy_** command you may deploy them as separate jars.
Note that the sources jar is not mandatory for the project to run, you may use it only if you want to see the sources of the SDK.
 
 - check that the dependencies used in **_build.gradle_** matches the **_groupId_**, **_artefactId_** and **_version_** as deployed in Nexus. In order to check that your dependencies are well resolved by gradle you may use the **dependencies** task.

 - there are some other dependency you need to add into your project in order to make it run. They are depicted in the readme file and you can find their exact **_groupId_**, **_artefactId_** and **_version_** in the pom file within the Mambu APIs project. 

If you have any further questions feel free to contact me

**Comment by azakordonets** [comment]
Thanks for the reply.  Regarding your points : 
1. Yes, I have my nexus repo in build.gradle file
2. Yes, it can handle multiple files - I can see both of them in my nexus repo
3. Yes, dependencies match to what I have specified, otherwise, my gradle task would fail on a step of getting dependency from Nexus. 
4. I have most of the specified dependencies in my project, but that's not the problem I was talking about. 

Let me add you couple more details : 
1. In Intellij IDEA I can see `Mambu-APIs-Java` library, however, unlike any other jar in my project - I can't see what's inside this jar.  When I try to unpack it - I get `Mambu-APIs-Java-6.0-bin.jar.cpgz` zip file. 
2. When I try to invoke `MambuAPIServiceFactory.getFactory` method, I get an error from Intellij IDEA that it doesn't know anything about `MambuAPIServiceFactory` class, though it's in my dependencies list. 

I have already tried to clone your project and package it myself, but I'm facing with the same issue - i can't anurchive it and find it's content + Intellij IDEA can't use it as a dependency as well.

**Comment by azakordonets** [comment]
@acostros Did as you suggested (though it doesn't matter since I can get dependency from Nexus as well, as I said before). The problem remains - I can't import `MambuAPIServiceFactory` - Intellij doesn't know where to take it from. I'm attaching screenshots as well. Please check the second screenshot with dependencies tree - Mambu API jar is closed and I cannot see it's internals, unlike guice.conf jar - there I have an error and it means that I have access to its internals. Mambu Java api jar is locked and that ( this is my guess ) is the reason why i can't import needed classes. 
![screenshot 2018-06-19 09 18 20](https://user-images.githubusercontent.com/1200012/41582514-26810b3e-73a2-11e8-9d8f-1d34a92fdaeb.png)
![screenshot 2018-06-19 09 18 45](https://user-images.githubusercontent.com/1200012/41582516-269d30ca-73a2-11e8-99c1-0f6793729f46.png)
![screenshot 2018-06-19 09 21 51](https://user-images.githubusercontent.com/1200012/41582551-3e0b1286-73a2-11e8-88b4-1f208a8530b5.png)

**Comment by azakordonets** [comment]
Here's one more thing to the picture. When i try to compile my project with gradle, i get this error messages : 
```
error: error reading /Users/andrew/Work/New10/Platform/system-integration/junit_system_integration/libs/mambu-models-V6.0.jar; error in opening zip file
error: error reading /Users/andrew/Work/New10/Platform/system-integration/junit_system_integration/libs/Mambu-APIs-Java-6.0-bin.jar; error in opening zip file
error: error reading /Users/andrew/Work/New10/Platform/system-integration/junit_system_integration/libs/Mambu-APIs-Java-6.0-bin-sources.jar; error in opening zip file
error: error reading /Users/andrew/Work/New10/Platform/system-integration/junit_system_integration/libs/mambu-models-V6.0.jar; error in opening zip file
error: error reading /Users/andrew/Work/New10/Platform/system-integration/junit_system_integration/libs/Mambu-APIs-Java-6.0-bin.jar; error in opening zip file
error: error reading /Users/andrew/Work/New10/Platform/system-integration/junit_system_integration/libs/Mambu-APIs-Java-6.0-bin-sources.jar; error in opening zip file
```

**Comment by acostros** [comment]
Please add the dependency directly into the project. At least we can see if the problem is caused by the Nexus usage or not. I've already deployed the SDK jars into Nexus and used them flawlessly.

The last message yous sen looks like the artefact is somehow corrupted.

The SDK jar can be opened with almost any unarchiver or if you add it into lib and instruct Gradle to use it the IntelliJ will allow you to expand it like you can do wit the other jars.

Regarding the forked project, if you want to generate yourself the jar just tun **mvn install** and the jar will be generated inside **_build_** folder.

**Comment by azakordonets** [comment]
Ok, found what was the problem - looks like Chrome has some security actions on downloaded jar's and they got corrupted - i did clean `mvn install` from the project and then put it into `lib` folder - now i see that this library is "opening' in Intellij IDEA, so it's a proper jar now. How can i build mambu-models jar ? Or maybe you can deploy it to maven central, so it would be available to everyone ?

**Comment by acostros** [comment]
Hi Andrew,

I'm glad that the SDK dependency issue was fixed.
Regarding the models jar you may use the one in the lib folder inside the Mambu-APIs project you just forked from Github, it should be one your local machine now. Just make sure you use the latest version.

**Comment by azakordonets** [comment]
Well, that's the thing - when i download this lib from your `lib` project folder, the jar looks like broken. I can't see it's content in Intellij IDEA. Is there a way that you deploy it to maven central, or i can build it myself ?

**Comment by azakordonets** [comment]
Ok, for now i just cloned your project, pushed your libraries to my Nexus and somehow it works. But i would suggest you to publish this libraries to central repo as well, cuz this way everyone will have an easy and clear way of getting your dependencies. 

Thanks for support and time.
